name: Prepare

description: Checkout and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
